/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lichao_opencv3_4_CameraViewActivity */

#ifndef _Included_com_lichao_opencv3_4_CameraViewActivity
#define _Included_com_lichao_opencv3_4_CameraViewActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lichao_opencv3_4_CameraViewActivity
 * Method:    initLoad
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_lichao_opencv3_14_CameraViewActivity_initLoad
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_lichao_opencv3_4_CameraViewActivity
 * Method:    faceDetect
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_lichao_opencv3_14_CameraViewActivity_faceDetect
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
